### ISSUE TITLE
Route unstranslated throws error

### ISSUE THREAD

**Issue by alexandrecruz** [royopa/trello-control-doc-pt-br#1]
"Unstranslated" page (from link "Arquivos ainda não traduzidos" in homepage) throws Internal Server Error.

**Comment by royopa** [comment]
@alexandrecruz Por favor, veja se o seu php.ini está setado com um tempo alto no max_execution_time. Essa página está demorando mais de 60 segundos para rodar, devido a quantidade de arquivos faltantes (mais de 9000) ou do método que estamos utilizando para fazer o crawler da página

**Comment by alexandrecruz** [comment]
@royopa Desculpe a falta de explanação, o erro está sendo apresentado no http://trello-control-doc-pt-br.esy.es/web/index_dev.php que foi enviado no chat do Gitter.

**Comment by royopa** [comment]
Ah, lá não tem jeito de corrigir, pois o problema está na configuração do
PHP.ini do hostinger, que não tenho acesso.

On Thu, Jan 1, 2015 at 12:06 PM, Alexandre Cruz notifications@github.com
wrote:

> @royopa https://github.com/royopa Desculpe a falta de explanação, o
> erro está sendo apresentado no
> http://trello-control-doc-pt-br.esy.es/web/index_dev.php que foi enviado
> no chat do Gitter.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/royopa/trello-control-doc-pt-br/issues/1#issuecomment-68487388
> .

## 

Rodrigo Prado de Jesus
http://about.me/royopa
royopa@gmail.com
